const projects = [
  {
    id: 1,
    category: "HTML",
    categoryName: "HTML & CSS",
    title: "The Next Website",
    lang: ["HTML", "CSS", "JS"],
    url: "https://github.com/Aycom366/The-Next-Website",
    live: "https://the-next-website.vercel.app/",
    slug: "next-website",
    info: "This Project was made back then when I Started my Web Design. It was made to actually text my css layout grids. and of cause, it responsive across all web surfer devices.\nThis was a small project which mostly consisted of HTML and CSS. I built a fully-responsive landing page. The only JavaScript this project required was to enable the toggling of the mobile navigation.\nThis Project was done to perfect setting down of reponsiveness in a website.",
    cat: "next",
    images: {
      mobil: "/images/portfolio/desktop/finshed-next.png",
      tablet: "/images/portfolio/tablet/finshed-next.png",
      desktop: "/images/portfolio/desktop/finshed-next.png",
    },
  },
  {
    id: 2,
    category: "HTML",
    categoryName: "HTML & CSS",
    title: "The Color Website",
    lang: ["HTML", "CSS", "JS"],
    url: "https://https://github.com/Aycom366/Color-Website",
    live: "https://http://color-website.vercel.app/",
    slug: "color-website",
    info: "This was a small project which mostly consisted of HTML and CSS. I built a fully-responsive landing page. The only JavaScript this project required was to enable the toggling of the mobile navigation.\nThis Project was done to perfect setting down of reponsiveness in a website.",
    cat: "next",
    images: {
      mobil: "/images/portfolio/desktop/color.png",
      tablet: "/images/portfolio/tablet/color.png",
      desktop: "/images/portfolio/desktop/color.png",
    },
  },
  {
    id: 3,
    category: "React",
    categoryName: "React",
    title: "Tip Calculator",
    lang: ["HTML", "CSS", "React"],
    url: "https://https://https://github.com/Aycom366/React-Tip-Calculator",
    live: "https://http://react-tip-calculator.vercel.app/",
    slug: "tip-website",
    info: "A simple Tip Calculator that calculates tip amount for various percentages of the cost of the service, and also provides a total amount that includes the tip.\nThis Project was done to perfect setting down of reponsiveness in a website.",
    cat: "next",
    images: {
      mobil: "/images/portfolio/desktop/Finshed-budget.png",
      tablet: "/images/portfolio/tablet/Finshed-budget.png",
      desktop: "/images/portfolio/desktop/Finshed-budget.png",
    },
  },
  {
    id: 4,
    category: "React",
    categoryName: "React",
    title: "AudioPhile",
    lang: ["HTML", "CSS", "React"],
    url: "https://https://https://github.com/Aycom366/React-Tip-Calculator",
    live: "https://http://react-tip-calculator.vercel.app/",
    slug: "audiophile-website",
    info: "A Fully fledged E-Commerce developed using React Framework. AudioPhile sells gadgets like Heaphones, EarPhones, Speakers of all models",
    cat: "next",
    images: {
      mobil: "/images/portfolio/desktop/Finshed-AudioPhile.png",
      tablet: "/images/portfolio/tablet/Finshed-AudioPhile.png",
      desktop: "/images/portfolio/desktop/Finshed-AudioPhile.png",
    },
  },
  {
    id: 3,
    category: "HTML",
    categoryName: "HTML && CSS",
    title: "Tip Calculator",
    lang: ["HTML", "CSS", "React"],
    url: "https://https://https://github.com/Aycom366/React-Tip-Calculator",
    live: "https://http://react-tip-calculator.vercel.app/",
    slug: "tip-website",
    info: "A Fully fledged E-Commerce developed using React Framework.\nThis Project was done to perfect setting down of reponsiveness in a website.",
    cat: "next",
    images: {
      mobil: "/images/portfolio/desktop/Finshed-AudioPhile.png",
      tablet: "/images/portfolio/tablet/Finshed-AudioPhile.png",
      desktop: "/images/portfolio/desktop/Finshed-AudioPhile.png",
    },
  },
];

export default projects;
